stage('Test') {
            agent {
                docker {
                    image 'python:3.9-alpine'
                    args '-u="root"'
                }
            }
            steps {
                // Вказуємо Jenkins зайти в папку з лабораторною
                dir('Lab_4_Tech_Prog') {
                    
                    // Спочатку видаляємо старі звіти (якщо є), щоб уникнути конфліктів
                    sh 'rm -rf test-reports'
                    
                    // Встановлюємо бібліотеки
                    sh 'pip install unittest-xml-reporting'
                    
                    // Тепер файл точно знайдеться
                    sh 'python test_app.py'
                }
            }
            post {
                always {
                    // Тут теж треба вказати правильний шлях до звітів
                    junit 'test-reports/*.xml'
                }
            }
        }